name: SSH into EC2 instance
on:
  push:
jobs:
  ssh:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: webfactory/ssh-agent@v0.5.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.BASTION_HOST_SSH_KEY }}" > ~/.ssh/BASTION_HOST_SSH_KEY
          chmod 600 ~/.ssh/BASTION_HOST_SSH_KEY
      - name: SSH into EC2 instance
        uses: appleboy/ssh-action@master
        with:
          host: 34.201.101.99
          username: kali
          port: 22
          script: |
            ls -al
            cd /tmp/zaproxy
            ls -al
