name: SSH into EC2 instance
on:
  push:
jobs:
  ssh:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Set up SSH key
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.BASTION_HOST_SSH_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
    - name: Get GitHub Actions IP address
      run: curl https://api.github.com/meta | grep actions
    - name: SSH into EC2 instance
      run: ssh -i ~/.ssh/id_rsa kali@34.201.101.99 "ls /tmp/zaproxy"
