name: ssh-into-aws-ec2

on:
  push:
    branches: [ "main" ]

#env:
#  bucket_name: "<example-bucket-name>"
 # AWS_REGION: us-east-1
  #REMOTE_HOST: "34.201.101.99"
  #REMOTE_USER: "kali"

permissions:
  contents: read
  id-token: write

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Git clone the repository
        uses: actions/checkout@v3
      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh
          cd ~/.ssh
          ssh-keyscan -H 34.201.101.99 >> ~/.ssh/known_hosts
          touch bastion_host_ssh_key.pem
          echo "${{secrets.BASTION_HOST_SSH_KEY}}" >> zaproxy-report-generator.pem
          chmod 400 zaproxy-report-generator.pem
          touch docker-ssh-installation-test.pem
          echo "${{secrets.DOCKER_INSTALLATION_KEY}}" >> docker-ssh-installation-test.pem
          chmod 400 docker-ssh-installation-test.pem
          ls -al
          ssh -i zaproxy-report-generator.pem kali@34.201.101.99 "ssh -i docker-ssh-installation-test.pem ubuntu@10.1.4.156"
      - name: Copy file to EC2
        uses: appleboy/scp-action@master
        with:
          host: 34.201.101.99
          username: kali
          key: ${{ secrets.DOCKER_INSTALLATION_KEY }} # or you can use a password instead of a key
          source: ~/.ssh
          target: ~/.ssh


      

